-- Create database if not exists
CREATE DATABASE IF NOT EXISTS orders;
USE orders;

-- USERS Table
CREATE TABLE IF NOT EXISTS USERS (
  USER_ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  ROLE ENUM('user', 'admin') DEFAULT 'user',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PRODUCT_CLASS Table (Categories)
CREATE TABLE IF NOT EXISTS PRODUCT_CLASS (
  PRODUCT_CLASS_CODE VARCHAR(10) PRIMARY KEY,
  PRODUCT_CLASS_DESC VARCHAR(100) NOT NULL
);

-- PRODUCT Table
CREATE TABLE IF NOT EXISTS product (
  PRODUCT_ID INT PRIMARY KEY,
  PRODUCT_DESC VARCHAR(60),
  PRODUCT_CLASS_CODE INT,
  PRODUCT_PRICE DECIMAL(12, 2),
  PRODUCT_QUANTITY_AVAIL INT,
  LEN INT,
  WIDTH INT,
  HEIGHT INT,
  WEIGHT DECIMAL(10, 4)
);

-- ORDER_HEADER Table
CREATE TABLE IF NOT EXISTS order_header (
  ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT,
  ORDER_DATE DATE DEFAULT NULL,
  ORDER_STATUS VARCHAR(10) DEFAULT NULL,
  PAYMENT_MODE VARCHAR(20) DEFAULT NULL,
  PAYMENT_DATE DATE DEFAULT NULL,
  ORDER_SHIPMENT_DATE DATE DEFAULT NULL,
  SHIPPER_ID INT DEFAULT NULL,
  SHIPPING_ADDRESS_ID INT DEFAULT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY (SHIPPER_ID) REFERENCES shipper(SHIPPER_ID),
  FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES address(ADDRESS_ID)
);

-- ORDER_ITEMS Table
CREATE TABLE IF NOT EXISTS order_items (
  ORDER_ID INT,
  PRODUCT_ID INT,
  PRODUCT_QUANTITY INT,
  PRIMARY KEY (ORDER_ID, PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES order_header(ORDER_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES product(PRODUCT_ID)
);

-- ADDRESS Table
CREATE TABLE IF NOT EXISTS ADDRESS (
  ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT,
  LABEL VARCHAR(50) DEFAULT 'Home',
  ADDRESS_LINE1 VARCHAR(255) NOT NULL,
  ADDRESS_LINE2 VARCHAR(255),
  CITY VARCHAR(100) NOT NULL,
  STATE VARCHAR(100),
  PINCODE VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(50) DEFAULT 'India',
  IS_DEFAULT TINYINT(1) DEFAULT 0,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(USER_ID)
);

-- SEED DATA 
INSERT IGNORE INTO PRODUCT_CLASS (PRODUCT_CLASS_CODE, PRODUCT_CLASS_DESC) VALUES 
('ELEC', 'Electronics'),
('CLOT', 'Clothing'),
('HOME', 'Home & Garden');

INSERT IGNORE INTO PRODUCT (PRODUCT_DESC, PRODUCT_CLASS_CODE, PRICE, STOCK_QUANTITY, IMAGE_URL) VALUES
('Smartphone Alpha', 'ELEC', 699.99, 50, 'https://images.unsplash.com/photo-1511707171634-1909a363a0a3?q=80&w=800&auto=format&fit=crop'),
('Wireless Headphones', 'ELEC', 149.99, 100, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop'),
('Classic Cotton T-Shirt', 'CLOT', 19.99, 200, 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop'),
('Denim Jeans', 'CLOT', 49.99, 150, 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=800&auto=format&fit=crop'),
('Ceramic Coffee Mug', 'HOME', 12.50, 300, 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?q=80&w=800&auto=format&fit=crop');
